### ISSUE TITLE
php8.2 compatibility?

### ISSUE THREAD

**Issue by cyberpunkbln** [Athlon1600/php-curl-client#2]
Hello,
youtube-dowloader are php8 ready but the composer version depends on this lib, that brings only on php8.2 this error:

```
composer\vendor\athlon1600\php-curl-client\src\CurlInfo.php
8192
Return type of Curl\CurlInfo::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

```
can you make it php8.2 compatible?

**Comment by k-komarov** [comment]
+1

**Comment by ndsda** [comment]
Since upgrading to PHP 8.2, I also get the same errors on line 75, 89, 106, and 120 in file CurlInfo.php

Is there an easy way to fix it, or a way to suppress the error?

**Comment by ndsda** [comment]
I added `#[\ReturnTypeWillChange]` before each function to suppress the error message.

**Comment by JamesSimpson** [comment]
Just came here with the same error on PHP 8.1

**Comment by JamesSimpson** [comment]
Can confirm @ndsda comment works by adding in `#[\ReturnTypeWillChange]` above each function within CurlInfo.php works as a workaround, but a little bit of a hacky way to "fix" the issue.

**Comment by ndsda** [comment]
It only suppresses the error and does not fix the issue with the return type. This method will very likely not work in future versions of PHP and will need to be fixed properly.
